### ISSUE TITLE
Tiny feedback

### ISSUE THREAD

**Issue by ViktorooReps** [epfml/getting-started#9]
Thank you for the comprehensive setup guide!

I have only one small confusion, in https://github.com/epfml/getting-started?tab=readme-ov-file#4-use-this-repo-to-start-a-job we need to replace `user.yaml` file with a template and fill in the fields according to the administrative data on EPFL website. 

At least in my account, there is GID present in the administrative data, and I am not sure if I should change the default GID in `templates/user_template.yaml`.

**Comment by martinjaggi** [comment]
@haeggee

**Comment by haeggee** [comment]
hey! thanks a lot for the feedback :) the GID in the template is set to the ID of our RCP MLO Group, so it shouldn't be changed for members of MLO (for reasons of file access permissions etc.)

**Comment by ViktorooReps** [comment]
@haeggee thanks! 

Maybe you could help me with my current issue (I am waiting for a helpdesk reply on this)

I am following https://github.com/epfml/getting-started?tab=readme-ov-file#minimal-basic-setup, and everything works well, the pod has started, I am able to connect to it, but I have no permissions to modify my own folder at `/mloscratch/homes/shcherba`:

```bash
(base) ➜ shcherba touch test
touch: cannot touch 'test': Permission denied
(base) ➜ shcherba id
uid=271312(shcherba) gid=75545(MLO-unit) groups=75545(MLO-unit)
(base) ➜ shcherba pwd
/mloscratch/homes/shcherba
```

Does it look like something that happened before? Otherwise I will just wait for a helpdesk response

**Comment by ViktorooReps** [comment]
```
(base) ➜  / cd mloscratch/homes/shcherba 
(base) ➜  shcherba touch test
(base) ➜  shcherba ls
conda  test
```
It works! Thank you very much @haeggee
